version: "3.8"

services:
  #mqtt Service
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    networks:
      - app-network       
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
  #Node-RED Service
  nodered:
    depends_on:
      - mqtt    
    container_name: node-red
    image: nodered/node-red:latest
    restart: always
    ports:
      - "1880:1880"
    networks:
      - app-network          
    volumes:
      - node_red_user_data:/data
    links:
      - "mariadb:mariadb"
networks:
  app-network:
    driver: bridge

volumes:
  node_red_user_data:
  mosquitto_persistence:
 
